name: CD
on:
  push:
    branches:
      - prod

jobs:
  deploy:
    name: Track Render Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Track Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ github.secret_source.RENDER_TOKEN }}
          render-variables: ${{ github.ENV.PROD_CLUSTER }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-cn6i9pocmk4c73e137u0
          retries: 20
          wait: 16000
          sleep: 30000
