name: CD

on:
  push:
    branches:
      - prod  # Modifier en fonction de votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to Render
        run: |
          npm install -g @render/cli
          render deploy -- --name lisaFlow --branch main
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_API_KEY }}
